In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes

In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [3]:
x,y=load_diabetes(return_X_y=True)

In [4]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [5]:
x_train

array([[ 0.00538306, -0.04464164,  0.05954058, ...,  0.05091436,
        -0.00422151, -0.03007245],
       [-0.02730979, -0.04464164,  0.08001901, ...,  0.00331192,
        -0.02952643,  0.03620126],
       [ 0.0090156 , -0.04464164, -0.02452876, ..., -0.00259226,
        -0.02139531,  0.00720652],
       ...,
       [-0.05273755,  0.05068012, -0.01806189, ...,  0.1081111 ,
         0.03606033, -0.04249877],
       [-0.00551455,  0.05068012, -0.00836158, ..., -0.00259226,
         0.08059005,  0.00720652],
       [-0.03457486,  0.05068012, -0.02560657, ..., -0.01550765,
         0.01482098,  0.04034337]])

In [6]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape # 442 rows and (10+1) columns

((353, 10), (89, 10), (353,), (89,))

In [7]:
lr=LinearRegression()

In [8]:
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
r2_score(y_test,y_pred)

0.5341988244945843

In [9]:
lr.intercept_   #. intercept value beta0

152.2555384904859

In [10]:
lr.coef_ # 10 columns so 10 coeffecients  beta1-beta10

array([  -3.88733451, -225.62527795,  517.90438059,  328.31029449,
       -727.20288812,  410.94784789,   80.2547038 ,  218.18152407,
        704.26613704,   40.02330705])

In [11]:
x_train.shape,x_train.shape[1]

((353, 10), 10)

In [12]:
class GDregressor:
   

    def __init__(self,learning_rate=0.01,epochs=100):
        self.coef=None     # we dont know how many coef will be there as this is may has multiple columns
        self.intercept=None
        self.lr=learning_rate
        self.epochs=epochs
    
    
    def fit(self,x_train,y_train):
        # initialize coef and intercept
        self.intercept=0. # as we start with value of 0 of intercept 
        
        # as we dont know how many columns are there so we use x_train to find number of columns
        self.coef=np.ones(x_train.shape[1]) # we start with value 1 of coef so we used np.ones
        
        # updating values of coef and intercept
        
        for i in range(self.epochs):
            
            
            # updating intercept
            
            y_hat= np.dot(x_train,self.coef) + self.intercept
            
            intercept_der = -2 * np.mean(y_train-y_hat)
            
            self.intercept=self.intercept - (self.lr * intercept_der)  # intercept_der = loss_slope_b
            
            
            
            # updating coef
            
            coef_der = -2 * np.dot((y_train-y_hat),x_train)/x_train.shape[0]
            
            self.coef=self.coef - (self.lr * coef_der)                 # coef_der=loss_slope_m
        
        
        print("intercept:",self.intercept,"coef",self.coef)
    
    
    def predict(self,x_test):
        return np.dot(x_test,self.coef) + self.intercept  #  y=mx+b
        


In [13]:
gdr=GDregressor(epochs=1000,learning_rate=0.5)

In [14]:
gdr.fit(x_train,y_train)

intercept: 152.06445047682317 coef [  17.03034296 -182.02825596  479.80706585  302.52707183  -37.48585206
  -98.9228287  -212.34819957  143.1467749   388.20540266   93.4142955 ]


In [15]:
lr.coef_

array([  -3.88733451, -225.62527795,  517.90438059,  328.31029449,
       -727.20288812,  410.94784789,   80.2547038 ,  218.18152407,
        704.26613704,   40.02330705])

In [16]:
lr.intercept_

152.2555384904859

In [17]:
y_pred=gdr.predict(x_test)

In [18]:
r2_score(y_test,y_pred)

0.5212482632291215